# Use root/example as user/password credentials
version: '3.1'

name: learnplay

services:
  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
    - "${REDIS_PORT}:6379"
  database:
    container_name: database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_USER: 'yes'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - my-db:/var/lib/mysql
  smtp:
    container_name: smtp
    image: jeanberu/mailcatcher
    ports: 
       - ${SMTP_DOCKER_PORT}:1080
volumes:
  my-db:
  cache:
    driver: local